name: root_access
description: Flutter plugin to get root access in Android device. This plugin is Android exclusive only.
version: 1.0.3
homepage: https://github.com/amitkhairnar44/root_access

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.amitkhairnar.rootaccess
        pluginClass: RootAccessPlugin